import { transformApiApplication } from './utils/stringToEnumMapping';

const mockApplications = [
  {
    id: 1,
    company: 'Google',
    position: 'Frontend Developer',
    status: 'INTERVIEW',
    appliedDate: '2023-11-15',
    platform: 'LinkedIn',
    notes: 'Recruiter contacted me first',
    link: 'https://fonts.google.com/',
  },
  {
    id: 2,
    company: 'Amazon',
    position: 'Backend Developer',
    status: 'Applied',
    appliedDate: '2023-11-20',
    platform: 'Career page',
    notes: 'Need to follow up',
    link: 'https://fonts.google.com/',
  },
  {
    id: 3,
    company: 'Microsoft',
    position: 'Full Stack Developer',
    status: 'Rejected',
    appliedDate: '2023-11-22',
    platform: 'Indeed',
    notes: 'No response after interview',
    link: '',
  },
  {
    id: 4,
    company: 'Facebook',
    position: 'Software Engineer',
    status: 'Accepted',
    appliedDate: '2023-12-01',
    platform: 'Career page',
    notes: 'Received an Accepted, reviewing it',
    link: '',
  },
  {
    id: 5,
    company: 'Netflix',
    position: 'Frontend Developer',
    status: 'Interview',
    appliedDate: '2023-12-05',
    platform: 'Referral',
    notes: 'Technical round scheduled',
    link: '',
  },
  {
    id: 6,
    company: 'Tesla',
    position: 'Backend Engineer',
    status: 'Applied',
    appliedDate: '2023-12-10',
    platform: 'Company website',
    notes: 'Application submitted, waiting for response',
    link: '',
  },
  {
    id: 7,
    company: 'Apple',
    position: 'iOS Developer',
    status: 'Interview',
    appliedDate: '2023-12-12',
    platform: 'LinkedIn',
    notes: 'Passed first round',
    link: '',
  },
  {
    id: 8,
    company: 'Uber',
    position: 'Mobile Developer',
    status: 'Rejected',
    appliedDate: '2023-12-15',
    platform: 'Recruiter email',
    notes: "Didn't pass coding test",
    link: '',
  },
  {
    id: 9,
    company: 'Airbnb',
    position: 'Frontend Developer',
    status: 'Accepted',
    appliedDate: '2023-12-18',
    platform: 'Career page',
    notes: 'Accepted received, considering',
    link: '',
  },
  {
    id: 10,
    company: 'Spotify',
    position: 'Backend Developer',
    status: 'Interview',
    appliedDate: '2023-12-20',
    platform: 'Glassdoor',
    notes: 'HR round next week',
    link: '',
  },
  {
    id: 11,
    company: 'Stripe',
    position: 'Software Engineer',
    status: 'Applied',
    appliedDate: '2023-12-22',
    platform: 'Referral',
    notes: 'Application submitted',
    link: '',
  },
  {
    id: 12,
    company: 'Twitter',
    position: 'Frontend Engineer',
    status: 'Rejected',
    appliedDate: '2023-12-25',
    platform: 'Career page',
    notes: 'Automated rejection email',
    link: '',
  },
  {
    id: 13,
    company: 'Snapchat',
    position: 'Backend Engineer',
    status: 'Interview',
    appliedDate: '2023-12-27',
    platform: 'Company website',
    notes: 'Waiting for second round feedback',
    link: '',
  },
  {
    id: 14,
    company: 'Pinterest',
    position: 'Full Stack Developer',
    status: 'Accepted',
    appliedDate: '2024-01-02',
    platform: 'Recruiter email',
    notes: 'Negotiating salary',
    link: '',
  },
  {
    id: 15,
    company: 'Shopify',
    position: 'Software Engineer',
    status: 'Applied',
    appliedDate: '2024-01-05',
    platform: 'Indeed',
    notes: 'Application in progress',
    link: '',
  },
  {
    id: 16,
    company: 'Adobe',
    position: 'Frontend Developer',
    status: 'Interview',
    appliedDate: '2024-01-08',
    platform: 'LinkedIn',
    notes: 'Panel interview scheduled',
    link: '',
  },
  {
    id: 17,
    company: 'Intel',
    position: 'Backend Engineer',
    status: 'Rejected',
    appliedDate: '2024-01-10',
    platform: 'Career page',
    notes: 'Failed technical round',
    link: '',
  },
  {
    id: 18,
    company: 'IBM',
    position: 'Cloud Engineer',
    status: 'Interview',
    appliedDate: '2024-01-12',
    platform: 'Recruiter email',
    notes: 'System design round next',
    link: '',
  },
  {
    id: 19,
    company: 'Oracle',
    position: 'DevOps Engineer',
    status: 'Accepted',
    appliedDate: '2024-01-15',
    platform: 'Referral',
    notes: 'Accepted accepted!',
    link: '',
  },
  {
    id: 20,
    company: 'Cisco',
    position: 'Network Engineer',
    status: 'Applied',
    appliedDate: '2024-01-18',
    platform: 'LinkedIn',
    notes: 'Awaiting recruiter response',
    link: '',
  },
  {
    id: 21,
    company: 'Salesforce',
    position: 'Software Engineer',
    status: 'Interview',
    appliedDate: '2024-01-20',
    platform: 'Career page',
    notes: 'Waiting for final round results',
    link: '',
  },
  {
    id: 22,
    company: 'Red Hat',
    position: 'Linux Engineer',
    status: 'Rejected',
    appliedDate: '2024-01-22',
    platform: 'Company website',
    notes: 'Skills mismatch',
    link: '',
  },
  {
    id: 23,
    company: 'LinkedIn',
    position: 'Machine Learning Engineer',
    status: 'Accepted',
    appliedDate: '2024-01-25',
    platform: 'Referral',
    notes: 'Exciting opportunity',
    link: '',
  },
  {
    id: 24,
    company: 'Twitch',
    position: 'Game Developer',
    status: 'Applied',
    appliedDate: '2024-01-27',
    platform: 'Recruiter email',
    notes: 'Passionate about gaming industry',
    link: '',
  },
  {
    id: 25,
    company: 'Dropbox',
    position: 'Backend Engineer',
    status: 'Interview',
    appliedDate: '2024-01-30',
    platform: 'Glassdoor',
    notes: 'Waiting for coding challenge',
    link: '',
  },
];

export const applicationsFromAPI = mockApplications.map((app: any) => {
  return transformApiApplication(app);
});
